# **Phase 1 — Data Investigation**

In [2]:
import pandas as pd

**Read CSV file**

In [3]:
df = pd.read_csv("../data/developer_ai_learning_raw.csv")

In [10]:
df.head()

,ResponseId,Age,YearsCode,DevType,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,AISelect,AIAcc,AISent
0,1,25-34 years old,14.0,"Developer, mobile","Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,"Yes, I use AI tools monthly or infrequently",Neither trust nor distrust,Indifferent
1,2,25-34 years old,10.0,"Developer, back-end","Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,"Yes, I use AI tools weekly",Neither trust nor distrust,Indifferent
2,3,35-44 years old,12.0,"Developer, front-end","Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,"Yes, I use AI tools daily",Somewhat trust,Favorable
3,4,35-44 years old,5.0,"Developer, back-end","Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,"Yes, I use AI tools weekly",Somewhat trust,Favorable
4,5,35-44 years old,22.0,Engineering manager,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,"Yes, I use AI tools weekly",Neither trust nor distrust,Favorable

In [11]:
df.sample(5)

,ResponseId,Age,YearsCode,DevType,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,AISelect,AIAcc,AISent
32756,32757,25-34 years old,NaN,NaN,"No, I am not new to coding and did not learn n...",NaN,NaN,NaN,NaN,NaN,NaN
21780,21781,18-24 years old,NaN,NaN,"Yes, I am not new to coding but am learning ne...",NaN,NaN,NaN,NaN,NaN,NaN
1195,1196,45-54 years old,41.0,"Developer, full-stack","Yes, I am not new to coding but am learning ne...",Stack Overflow or Stack Exchange;Technical doc...,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,"Yes, I use AI tools daily",Somewhat distrust,Very favorable
2527,2528,18-24 years old,7.0,Student,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I didn't spend time learning in the past year",NaN,"No, and I don't plan to",Highly distrust,Unfavorable
48809,48810,35-44 years old,31.0,"Developer, back-end","Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Videos (no...,NaN,NaN,NaN

**Data Shape**

In [6]:
df.shape

(49191, 11)

**Columns Names**

In [7]:
df.columns

Index(['ResponseId', 'Age', 'YearsCode', 'DevType', 'LearnCodeChoose',
       'LearnCode', 'LearnCodeAI', 'AILearnHow', 'AISelect', 'AIAcc',
       'AISent'],
      dtype='str')

**Info Dataset**

In [97]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ResponseId       49191 non-null  int64
 1   Age              49191 non-null  str
 2   YearsCode        43042 non-null  float64
 3   DevType          43680 non-null  str
 4   LearnCodeChoose  46858 non-null  str
 5   LearnCode        33556 non-null  str
 6   LearnCodeAI      45201 non-null  str
 7   AILearnHow       28257 non-null  str
 8   AISelect         33720 non-null  str
 9   AIAcc            33297 non-null  str
 10  AISent           33467 non-null  str
dtypes: float64(1), int64(1), str(9)
memory usage: 4.1 MB

In [12]:
df.dtypes

ResponseId           int64
Age                    str
YearsCode          float64
DevType                str
LearnCodeChoose        str
LearnCode              str
LearnCodeAI            str
AILearnHow             str
AISelect               str
AIAcc                  str
AISent                 str
dtype: object

In [13]:
df.isna().sum()

ResponseId             0
Age                    0
YearsCode           6149
DevType             5511
LearnCodeChoose     2333
LearnCode          15635
LearnCodeAI         3990
AILearnHow         20934
AISelect           15471
AIAcc              15894
AISent             15724
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(0)

In [21]:
df.nunique()

ResponseId         49191
Age                    7
YearsCode             78
DevType               32
LearnCodeChoose        3
LearnCode           2767
LearnCodeAI            5
AILearnHow          1677
AISelect               5
AIAcc                  5
AISent                 6
dtype: int64

In [75]:
df["YearsCode"].unique()

array([ 14.,  10.,  12.,   5.,  22.,  20.,  13.,  30.,  15.,   9.,   6.,
        nan,   3.,  40.,   8.,  45.,  35.,  11.,   7.,  47.,  41.,  36.,
        23.,  29.,  26.,  25.,  38.,  21.,  19.,  18.,  16.,   4.,  17.,
        42.,  27.,  24.,   2.,  28.,  37.,  32.,   1.,  39.,  53.,  33.,
        50.,  48.,  44.,  31.,  46.,  43.,  49.,  52.,  34.,  51.,  58.,
        57.,  54.,  63.,  60.,  55.,  65., 100.,  99.,  56.,  69.,  90.,
        61.,  67.,  75.,  64.,  98.,  68.,  89.,  62.,  78.,  70.,  76.,
        82.,  59.])

# **Phase 2 - Cleaning**

In [4]:
df["YearsCode"] = df["YearsCode"].astype("Int64")

In [5]:
df["LearnCode"] = df["LearnCode"].str.split(";")

In [6]:
df["AILearnHow"] = df["AILearnHow"].str.split(";")

In [7]:
df.to_json("../data/cleaned_data.jsonl", orient="records",lines=True)

# **Phase 3 — Analysis**

In [31]:
df["LearnCode"].explode().value_counts()

LearnCode
Technical documentation (is generated for/by the tool or system)          22739
Other online resources (e.g. standard search, forum, online community)    19701
Stack Overflow or Stack Exchange                                          17245
Videos (not associated with specific online course or certification)      16771
AI CodeGen tools or AI-enabled apps                                       14753
Blogs or podcasts                                                         11688
Online Courses or Certification (includes all media types)                10973
Books / Physical media                                                    10187
Colleague or on-the-job training                                           8596
School (i.e., University, College, etc)                                    5561
Games or coding challenges                                                 4046
Coding Bootcamp                                                            1747
Other (please specify):                                                    1068
Name: count, dtype: int64

In [20]:
df["AILearnHow"].explode().value_counts().head(1)

AILearnHow
AI CodeGen tools or AI-enabled apps    14824
Name: count, dtype: int64

In [15]:
df["AIAcc"].value_counts()

AIAcc
Somewhat trust                9869
Somewhat distrust             8685
Neither trust nor distrust    7162
Highly distrust               6533
Highly trust                  1048
Name: count, dtype: int64

In [16]:
df["AISelect"].value_counts()

AISelect
Yes, I use AI tools daily                      15883
Yes, I use AI tools weekly                      5958
No, and I don't plan to                         5454
Yes, I use AI tools monthly or infrequently     4628
No, but I plan to soon                          1797
Name: count, dtype: int64

# **"Phase 4 — Enrichment"**

In [51]:
def experience_level(years_code):
    if pd.isna(years_code):
        return "Unknown"
    if years_code <= 2:
        return "Beginner"
    if years_code <= 5:
        return "Early Career"
    if years_code <= 10:
        return "Experienced"
    return "Highly Experienced"

In [52]:
df["ExperienceLevel"] = df["YearsCode"].apply(experience_level)

KeyError: 'YearsCode'

In [32]:
df["ExperienceLevel"].value_counts()

ExperienceLevel
Highly Experienced    25817
Experienced           10365
Unknown                6149
Early Career           5153
Beginner               1707
Name: count, dtype: int64

In [34]:
df["LearnCode"].explode().unique()

<StringArray>
[            'Online Courses or Certification (includes all media types)',
 'Other online resources (e.g. standard search, forum, online community)',
                                                 'Books / Physical media',
   'Videos (not associated with specific online course or certification)',
                                       'Stack Overflow or Stack Exchange',
       'Technical documentation (is generated for/by the tool or system)',
                                    'AI CodeGen tools or AI-enabled apps',
                                                                      nan,
                                       'Colleague or on-the-job training',
                                                      'Blogs or podcasts',
                                                        'Coding Bootcamp',
                                             'Games or coding challenges',
                                'School (i.e., University, College, etc)',
                                                'Other (please specify):']
Length: 14, dtype: str

In [33]:
def uses_documentation(learn_code_list):
    if type(learn_code_list) is not list:
        return False
    return "Technical documentation (is generated for/by the tool or system)" in learn_code_list

df["usesDocumentation"] = df["learnCode"].apply(uses_documentation)

In [35]:
def uses_ai_for_learning(learn_code_list):
    if type(learn_code_list) is not list:
        return False
    return "AI CodeGen tools or AI-enabled apps" in learn_code_list

df["usesAIForLearning"] = df["LearnCode"].apply(uses_ai_for_learning)

In [54]:
def uses_stack_overflow(learn_code_list):
    if type(learn_code_list) is not list:
        return False
    return "Stack Overflow or Stack Exchange" in learn_code_list

df["usesStackOverflow"] = df["learningMethods"].apply(uses_stack_overflow)

In [40]:
df["usesStackOverflow"].value_counts()

usesStackOverflow
False    34438
True     14753
Name: count, dtype: int64

In [46]:
df = df.rename(columns={
    'ResponseId': 'responseId',
    'Age': 'age',
    'YearsCode': 'yearsCode',
    'DevType': 'devType',
    'LearnCodeChoose': 'learnCodeChoose',
    'LearnCode': 'learningMethods',
    'LearnCodeAI': 'learnCodeAI',
    'AILearnHow': 'aiLearningMethods',
    'AISelect': 'aiUsage',
    'AIAcc': 'aiTrust',
    'AISent': 'aiSentiment',
    "ExperienceLevel" : "experienceLevel"
})

In [55]:
df.columns

Index(['responseId', 'age', 'yearsCode', 'devType', 'learnCodeChoose',
       'learningMethods', 'learnCodeAI', 'aiLearningMethods', 'aiUsage',
       'aiTrust', 'aiSentiment', 'experienceLevel', 'usesDocumentation',
       'usesAIForLearning', 'usesStackOverflow'],
      dtype='str')

In [56]:
df.to_json("../data/enriched_data.jsonl", orient="records", lines=True)